version: "3.9"

services:

    database:
        image: mongo
        container_name: 'clear-db'
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=clear
            - MONGO_INITDB_ROOT_PASSWORD=clear
            - MONGO_INITDB_DATABASE=clear_api

        volumes:
            - ./.volumes/mongo:/data/db
        networks:
            - default

    api:
        build:
            context: .
            dockerfile: ./infrastructure/docker/dev/node/Dockerfile
        container_name: 'clear-api'
        ports:
            - '8000:8000'
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database
        networks:
            - default
