version: "3.9"

services:

    database:
        image: mongo
        container_name: 'clear-db'
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=clear
            - MONGO_INITDB_ROOT_PASSWORD=clear
            - MONGO_INITDB_DATABASE=clear_api

        volumes:
            - ./.volumes/mongo:/data/db
        networks:
            - default